/**
 * Copyright (c) 2020 Carlos Gonçalves (https://www.linkedin.com/in/carlosmogoncalves/)
 * Likely open-source, so copy at will, bugs will be yours as well.
 */
package pt.cmg.aeminium.knowledge.api.rest.filters.request;

import java.io.Serializable;
import pt.cmg.aeminium.knowledge.persistence.entities.localisation.Language;

/**
 * This object will hold Request data that is filled in every request.
 * It is contextual data like the expected response language, the device type that performed the request
 * or any other kind of volatile data that is somehow relevant to the current request.
 * <br>
 * It is suposed to be filled before the request hits the resource function by a chain of filters.
 *
 * @author Carlos Gonçalves
 */
public class RequestContextData implements Serializable {

    /**
     * Auto-generated by IDE
     */
    private static final long serialVersionUID = 2643263275423254609L;

    private Language selectedLanguage;
    private ClientApplicationData appData;

    public Language getSelectedLanguage() {
        return selectedLanguage == null ? Language.DEFAULT_LANGUAGE : selectedLanguage;
    }

    public void setSelectedLanguage(Language selectedLanguage) {
        this.selectedLanguage = selectedLanguage;
    }

    public ClientApplicationData getAppData() {
        return appData;
    }

    public void setAppData(ClientApplicationData appData) {
        this.appData = appData;
    }

}
