/**
 * Copyright (c) 2020 Carlos Gonçalves (https://www.linkedin.com/in/carlosmogoncalves/)
 * Likely open-source, so copy at will, bugs will be yours as well.
 */
package pt.cmg.aeminium.knowledge.persistence.entities.schools;

import java.io.Serializable;
import java.time.LocalDateTime;
import java.util.List;
import java.util.Objects;
import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.NamedQuery;
import jakarta.persistence.OneToMany;
import jakarta.persistence.OneToOne;
import jakarta.persistence.SequenceGenerator;
import jakarta.persistence.Table;
import org.eclipse.persistence.annotations.Cache;
import org.eclipse.persistence.annotations.CacheCoordinationType;
import org.eclipse.persistence.annotations.CacheType;
import org.eclipse.persistence.config.CacheIsolationType;
import pt.cmg.aeminium.knowledge.persistence.entities.identity.User;

/**
 * @author Carlos Gonçalves
 */
@Entity
@Table(name = "Courses")
@Cache(type = CacheType.FULL, isolation = CacheIsolationType.SHARED, alwaysRefresh = true, coordinationType = CacheCoordinationType.SEND_NEW_OBJECTS_WITH_CHANGES)
@NamedQuery(name = Course.QUERY_FIND_ALL, query = "SELECT c from Course c")
@NamedQuery(name = Course.QUERY_FIND_BY_NAME,
    query = "SELECT c from Course c WHERE c.nameTextContentId = (SELECT tc.id FROM TextContent tc WHERE tc.textValue = :name)")
@NamedQuery(name = Course.QUERY_FIND_BY_TRANSLATED_NAME,
    query = "SELECT c from Course c WHERE c.nameTextContentId = (SELECT tc.id FROM TranslatedText tc WHERE tc.language = :language AND tc.textValue = :name)")
public class Course implements Serializable {

    /**
     * Auto-generated by IDE
     */
    private static final long serialVersionUID = 4430445702440386925L;

    public static final String QUERY_FIND_ALL = "Course.findAll";
    public static final String QUERY_FIND_BY_NAME = "Course.findByName";
    public static final String QUERY_FIND_BY_TRANSLATED_NAME = "Course.findByTranslatedName";

    @Id
    @SequenceGenerator(
        sequenceName = "courses_id_seq",
        allocationSize = 1,
        initialValue = 1,
        name = "COURSES_SEQUENCE")
    @GeneratedValue(
        strategy = GenerationType.SEQUENCE,
        generator = "COURSES_SEQUENCE")
    @Column(name = "id")
    private Long id;

    @Column(name = "acronym", nullable = false)
    private String acronym;

    @Column(name = "image", nullable = true)
    private String image;

    @OneToOne(optional = false, fetch = FetchType.LAZY)
    @JoinColumn(name = "school", referencedColumnName = "id")
    private School school;

    @Column(name = "year", nullable = false)
    private int year;

    @Column(name = "name")
    private Long nameTextContentId;

    @Column(name = "description")
    private Long descriptionContentId;

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "course")
    private List<CourseClass> courseClasses;

    @Column(name = "createdat")
    private LocalDateTime createdAt;

    @OneToOne(optional = false, fetch = FetchType.LAZY)
    @JoinColumn(name = "createdby", referencedColumnName = "id")
    private User createdBy;

    public Course() {
        this.createdAt = LocalDateTime.now();
    }

    public Long getId() {
        return id;
    }

    public String getAcronym() {
        return acronym;
    }

    public String getImage() {
        return image;
    }

    public int getYear() {
        return year;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public void setAcronym(String acronym) {
        this.acronym = acronym;
    }

    public void setImage(String image) {
        this.image = image;
    }

    public void setYear(int year) {
        this.year = year;
    }

    public School getSchool() {
        return school;
    }

    public void setSchool(School school) {
        this.school = school;
    }

    public List<CourseClass> getCourseClasses() {
        return courseClasses;
    }

    public void setCourseClasses(List<CourseClass> courseClasses) {
        this.courseClasses = courseClasses;
    }

    public void addCourseClass(CourseClass courseClass) {
        this.courseClasses.add(courseClass);
    }

    public Long getNameTextContentId() {
        return nameTextContentId;
    }

    public void setNameTextContentId(Long nameTextContentId) {
        this.nameTextContentId = nameTextContentId;
    }

    public Long getDescriptionContentId() {
        return descriptionContentId;
    }

    public void setDescriptionContentId(Long descriptionContentId) {
        this.descriptionContentId = descriptionContentId;
    }

    public LocalDateTime getCreatedAt() {
        return createdAt;
    }

    public User getCreatedBy() {
        return createdBy;
    }

    public void setCreatedBy(User createdBy) {
        this.createdBy = createdBy;
    }

    @Override
    public int hashCode() {
        return Objects.hash(id);
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj) {
            return true;
        }
        if (obj == null) {
            return false;
        }
        if (getClass() != obj.getClass()) {
            return false;
        }
        Course other = (Course) obj;
        return Objects.equals(id, other.id);
    }

}
