/**
 * Copyright (c) 2020  Carlos Gonçalves (https://www.linkedin.com/in/carlosmogoncalves/)
 * Likely open-source, so copy at will, bugs will be yours as well.
 */
package pt.sweranker.persistence.entities.degrees;

import java.io.Serializable;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.EnumType;
import javax.persistence.Enumerated;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

/**
 * @author Carlos Gonçalves
 */
@Entity
@Table(name = "Courses")
public class Course implements Serializable {

    /**
     * Auto-generated by IDE
     */
    private static final long serialVersionUID = 4430445702440386925L;

    @Id
    @GeneratedValue(strategy = GenerationType.SEQUENCE)
    @SequenceGenerator(name = "courses_id_seq")
    private Long id;

    @Column(name = "acronym", nullable = false)
    private String acronym;

    @Column(name = "image", nullable = true)
    private String image;

    @Column(name = "university", nullable = false)
    @Enumerated(EnumType.STRING)
    private University university;

    @Column(name = "year", nullable = false)
    private int year;

    public Long getId() {
        return id;
    }

    public String getAcronym() {
        return acronym;
    }

    public String getImage() {
        return image;
    }

    public University getUniversity() {
        return university;
    }

    public int getYear() {
        return year;
    }

}
