/**
 * Copyright (c) 2020 Carlos Gonçalves (https://www.linkedin.com/in/carlosmogoncalves/)
 * Likely open-source, so copy at will, bugs will be yours as well.
 */
package pt.sweranker.persistence.entities.degrees;

import java.io.Serializable;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.EnumType;
import javax.persistence.Enumerated;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import pt.sweranker.persistence.entities.schools.School;

/**
 * @author Carlos Gonçalves
 */
@Entity
@Table(name = "Courses")
public class Course implements Serializable {

    /**
     * Auto-generated by IDE
     */
    private static final long serialVersionUID = 4430445702440386925L;

    @Id
    @SequenceGenerator(
        sequenceName = "courses_id_seq",
        allocationSize = 1,
        initialValue = 1,
        name = "COURSES_SEQUENCE")
    @GeneratedValue(
        strategy = GenerationType.SEQUENCE,
        generator = "COURSES_SEQUENCE")
    @Column(name = "id")
    private Long id;

    @Column(name = "acronym", nullable = false)
    private String acronym;

    @Column(name = "image", nullable = true)
    private String image;

    @Column(name = "university", nullable = false)
    @Enumerated(EnumType.STRING)
    private School university;

    @Column(name = "year", nullable = false)
    private int year;

    public Long getId() {
        return id;
    }

    public String getAcronym() {
        return acronym;
    }

    public String getImage() {
        return image;
    }

    public School getUniversity() {
        return university;
    }

    public int getYear() {
        return year;
    }

}
