/**
 * Copyright (c) 2020  Carlos Gonçalves (https://www.linkedin.com/in/carlosmogoncalves/)
 * Likely open-source, so copy at will, bugs will be yours as well.
 */
package pt.sweranker.persistence.entities.degrees;

import java.io.Serializable;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.EnumType;
import javax.persistence.Enumerated;
import javax.persistence.Id;

/**
 * @author Carlos Gonçalves
 */
@Entity(name = "Degrees")
public class Degree implements Serializable {

    /**
     * Auto-generated by IDE
     */
    private static final long serialVersionUID = 4430445702440386925L;

    @Id
    private Long id;

    @Column(name = "acronym", nullable = false)
    private String acronym;

    @Column(name = "image", nullable = true)
    private String image;

    @Column(name = "university", nullable = false)
    @Enumerated(EnumType.STRING)
    private University university;

    @Column(name = "year", nullable = false)
    private int year;

}
