/**
 * Copyright (c) 2020  Carlos Gonçalves (https://www.linkedin.com/in/carlosmogoncalves/)
 * Likely open-source, so copy at will, bugs will be yours as well.
 */
package pt.sweranker.persistence.knowledgeareas;

import java.io.Serializable;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.SequenceGenerator;

/**
 * @author Carlos Gonçalves
 */
@Entity(name = "topics")
public class Topic implements Serializable {

    /**
     * Auto-generated by IDE
     */
    private static final long serialVersionUID = 6025578077962121721L;

    @Id
    @GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "TOPIC_SEQUENCE")
    @SequenceGenerator(name = "TOPIC_SEQUENCE",
        sequenceName = "topic_id_seq",
        initialValue = 1,
        allocationSize = 1)
    private Long id;

    public Long getId() {
        return id;
    }

}
