/**
 * Copyright (c) 2020  Carlos Gonçalves (https://www.linkedin.com/in/carlosmogoncalves/)
 * Likely open-source, so copy at will, bugs will be yours as well.
 */
package pt.sweranker.filters.request;

import java.io.Serializable;
import pt.sweranker.persistence.entities.Language;

/**
 * @author Carlos Gonçalves
 */
public class RequestPayload implements Serializable {

    /**
     * Auto-generated by IDE
     */
    private static final long serialVersionUID = 2643263275423254609L;

    public Language selectedLanguage;
    public ClientApplicationData appData;

    public Language getSelectedLanguage() {
        return selectedLanguage;
    }

    public void setSelectedLanguage(Language selectedLanguage) {
        this.selectedLanguage = selectedLanguage;
    }

    public ClientApplicationData getAppData() {
        return appData;
    }

    public void setAppData(ClientApplicationData appData) {
        this.appData = appData;
    }

}
